---
version: '3'
services:
  api:
    image: svbailey/ua_api_v1
    depends_on:
      - db
    environment:
      - POSTGRES_DB=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
  db:
    image: svbailey/ua_db_v1
    environment:
      - POSTGRES_DB=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio

